server:
  port: 8001

dubbo:
  application:
    # 应用名称
    name: provider
  registry:
    # 注册中心地址
    address: multicast://224.5.6.7:1234
    # 超时时间，单位毫秒
    timeout: 6000
  protocol:
    # 协议名称
    name: dubbo
    # 协议端口
    port: 28001
